### ISSUE TITLE
Search results refresh and give different results

### ISSUE THREAD

**Issue by cgpirre** [OsaSoft/youtube-better-subscriptions#114]
When searching on youtube with the extension enabled, it'll show the results, and then a second or so later the page refreshes by itself and other results are shown.
Pressing the search button again will keep showing the 'new' results, so will opening a new tab and searching the same term.

However, refreshing the actual page will restore the original results, and they will stay even when pressing the search button again. But opening a new tab and searching the same terms will again show the original results, refresh by itself, and show the 'new' results. The other tab will keep showing the right results though, no matter what I do.

**Comment by BenjiK4** [comment]
Same issue happens for me too. Using the latest version of Firefox.
It is impossible to search for videos as the search results always refresh to loosely related results.
Sadly I can't use this addon in this current state.

**Comment by grandslammer** [comment]
Same issue is happening for me also. Very frustrating bug.

**Comment by grandslammer** [comment]
Bumping this due to being so frustrated from having to temporarily disable the extension every time I want to search for anything on YouTube.
Is this extension still being maintained?

**Comment by OsaSoft** [comment]
Sorry, Ibve been extremely busy and havent had time to work on the extension at all. 
I was wondering why I havent seen this happen but now I understand. It (seems to) only happens when starting the search on the subscriptions page, so a temporary workaround would be to first go to the yt home page (ie click the yt logo) and then search. Thats how i have usually done it, by opening the search in a new window since i want to keep my subs feed open in a separate tab and why i havent seen this error before.

I know its not the solution you guys deserve, but until I have some time or someone else pitches in it should at least be better than disabling the extension

**Comment by cgpirre** [comment]
That already helps a ton, thanks!
And many thanks for the great extension, it's a big improvement to my daily internet use <3

**Comment by OsaSoft** [comment]
is this still happening?

**Comment by cgpirre** [comment]
> is this still happening?

I just checked, it seems to be fixed, many thanks!
