### ISSUE TITLE
Extension no longer hides videos watched on phone

### ISSUE THREAD

**Issue by grandslammer** [OsaSoft/youtube-better-subscriptions#131]
So I opened YouTube on my PC this morning and noticed that some subscription videos which I watched on my iPhone last night are no longer being hidden. Previously, the extension automatically detected those videos as watched and hid them automatically.

Opening the same videos on my PC for a few seconds does hide them.

I assume this is being caused by some new YouTube update.

**Comment by RensReus** [comment]
I have the same problem except on multiple PCs. The extension doesn't seem to be able to detect the watched videos on different devices.

**Comment by OsaSoft** [comment]
When working across devices, the only way atm is to use Youtubes's watched gauge under the videos to tell wether it has been seen or not. Check if that setting is on, but I have noticed that YT is pretty inconsistent with displaying the gauge.
There is currently a PR #151 to use sync browser storage, so that will sync between PC browsers with the extension installed, but unfortunately there is no real way to detect it in the mobile apps
