### ISSUE TITLE
Prettier Mark as watched button

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#16]
Style the button better, possibly move it to a different spot

**Comment by macearl** [comment]
I was kind of annoyed by the changing button location due to different video titles, so I tried my luck at a new position and new look.

I created a pull request for it (i thought this would be the easiest way to share the changes, even if they are not intended to be merged)

PR: https://github.com/OsaSoft/youtube-better-subscriptions/pull/24

**Comment by OsaSoft** [comment]
Sorry it took me so long. I just finished up some final touches, along with some new features and the update should be coming through very soon!
