### ISSUE TITLE
Update 0.19.1 not working in Chrome and options page has infinite loading spinners

### ISSUE THREAD

**Issue by grandslammer** [OsaSoft/youtube-better-subscriptions#171]
I just updated to 0.19.1 and noticed that the extension is not hiding watched videos. The "Hide Watched" and "Mark All As Watched" are also not displaying.

I checked the options page and also noticed that there are infinite loading spinners for each option - see screenshot below.

![image](https://github.com/OsaSoft/youtube-better-subscriptions/assets/18541062/e94dd41c-97c9-4f31-8cde-fcb8591244ab)

**Comment by sek0n** [comment]
I had this same problem on vivaldi today when I got on. Noticed it was also doing it with another extension. I closed out of vivaldi completely(as in closing out the background service from the system tray too), and restarted.

All seems to be working again after that.

**Comment by grandslammer** [comment]
Issue seems to resolved itself, though I did a full restart of Chrome several times today. No explanation as to either the cause of the issue or how it randomly resolved itself. I will update here if it occurs again.

**Comment by grandslammer** [comment]
I also noticed that the "Mark All as Watched" button is causing the subscriptions tab to go non-responsive upon clicking it.

**Comment by NavinSangtani** [comment]
Hi, 
Since updating to the latest version the extension is unusable, it breaks the functionality of Chrome. The moment I enable it and open youtube chrome my CPU usage shoots up and the crowser freezes, Also none of the features of the extension are present on chrome, its as if the extension was not installed (toggle and "Mark all as watched" not disappeared) and watched videos are not being hidden anymore.
I tried disabling all my extensions and enabling this one alone to see if it was conflicting with another extension but the issue persists.

**Comment by OsaSoft** [comment]
I believe this might be a side effect of using the sync storage for watched videos as the first run after the upgrade would try to push everything into the sync storage, which might take a while on a slower connection and/or computer 🤔 
That would also explain the mark all as watched that @grandslammer mentioned, since itd be trying to push everything in the current feed into the sync and javascript that does in a blocking way...
Maybe there is some way to use background runners to improve this behaviour
