### ISSUE TITLE
Mark All As Watched button

### ISSUE THREAD

**Issue by mvdgb** [OsaSoft/youtube-better-subscriptions#23]
Love the extension; thanks for creating it.

I'd like to see a "Mark All As Watched" or "Mark All Videos in the Current View as Watched" button that would allow me to avoid having to click the Mark As Watched button for each video in the subscription grid. Sometimes I just want to clear the whole thing out.

Thanks and regards.

**Comment by OsaSoft** [comment]
Hi, thanks for the feedback, glad you like the extension!

A "Mark all as watched" sounds pretty reasonable. Ill put it on my todo list :)

**Comment by grandslammer** [comment]
Any update on this? This feature would be amazing! There was another extension which I used to use which did this, but it seems the developer has stopped updating it. https://github.com/CodeNinjaUK/youtube-subs-grid

**Comment by OsaSoft** [comment]
@grandslammer hey, this is fairly low on my priorities to be honest, as I personally dont really see the use for it. 
But yeah, Subs Grid by CodeNinjaUK had the feature, which is why I am planning to add it, as the discontinuation of that extension is the reason I decided to make my own and its a major inspiration to everything this extension does

**Comment by OsaSoft** [comment]
One question though:
Would you guys prefer the "Mark all as watched" to be for EVERYTHING currently visible in the feed, or for the individual sections? Ie. "Today", "Yesterday", "This week", etc.

**Comment by grandslammer** [comment]
It would greatly increase the speed at which I skim through my videos. I always start at the oldest video I haven't seen and work my way up the page to the latest video. A Mark All As Watched would save me time from having to read the title of videos I don't want to watch (say if a particular channel uploads a video I don't have interest in watching on that particular day). Subs Grid by CodeNinjaUK saved me from having to do that and when you use YouTube as much as I do, that time adds up :)

Subs Grid by CodeNinjaUK marked everything as watched but it also changed the subs grid to show every video in one block rather than by day/week from what I recall. I would be open to testing both and everything version and an individual sections version. An everything version would help keep the subs page cleaner and remove the clutter of videos I don't want to watch, but an individual sections version might have its own advantages.

**Comment by mvdgb** [comment]
It doesn't matter to me whether it's for everything or for sections. I usually pick through the new stuff and open new links or add them to my Watch Later list once or twice a day, then clear everything out so I don't have repeats. Thanks for considering this feature.

**Comment by OsaSoft** [comment]
I see. It's cool to see how different people use things in ways I didn't even think of. I'll definitely put this feature on a higher priority, as it shouldn't take long and you guys seem to find great use for it

**Comment by OsaSoft** [comment]
Update! Finally managed to get this working properly. Version 0.6.1 adds this functionality and should be rolling out soon.

Resolved by #29
