### ISSUE TITLE
mark as watched on youtube itself?

### ISSUE THREAD

**Issue by AlJohri** [OsaSoft/youtube-better-subscriptions#38]
is there anyway to mark as watched on youtube's watch history itself? I'd love to click a button and have and mark a video as watched and also have it appear in https://www.youtube.com/feed/history

related: https://github.com/sniklaus/youtube-watchmarker/issues/14

**Comment by OsaSoft** [comment]
Hey, I have been trying to find a way to do this, but sadly havent come up with anything yet

**Comment by OsaSoft** [comment]
After some reasearch, YTs watchtime endpoints rely on specific playback ids and have quite a lot of anti-tampering protection, which makes sense.
This means, that its prett much impossible...
Also, since YTs 'watched' is fairly unreliable and sometimes disappears randomly, in the future the plan is to rely on it as little as possible.

However, having the marked videos show up in history is a nice idea, and Ive created a new ticket for that, see #54
