### ISSUE TITLE
Config page

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#51]
Add a page where different things relating to the addon can be configured. Things like: refresh rate, logging, sync or local storage (therefore whether saved elems are permanent #20 #22 #33 , or how many to keep in history), whether to use YTs mark as watched (#33) , etc

**Comment by Eds1989** [comment]
As an extension of this enhancement, I would like to be able to configure the conditions on what the extension considers to be "watched".

For example, I personally want partially watched videos to be visible in my feed, until I have watched either a percentage, or all the way through. If I start watching a video on my phone, then later want to pick up where I left off, this extension has hidden the video. Being able to exclude partial watches, or configure a watched percentage would be nice.

**Comment by Eds1989** [comment]
Another nice option to be able to configure, is to prevent the page loading videos older than a certain age (think Plex's On Deck feature if you have used Plex. You can specify an age of videos to appear On Deck before they get removed automatically).

Reasoning behind this:
My goal is to have an empty feed so I know I am 100% up to date.
If I mark all videos as watched, the page will go blank, but then starting loading older videos.
You can mark all as watched again, but it will then load even older videos. I could keep doing this of course, but would have to do it so many times to mark all of my years worth of videos as watched it's not a feasible option.

It would be great to prevent YouTube loading any additional videos past a certain age, so that a blank feed can be maintained.

**Comment by OsaSoft** [comment]
@Eds1989 thanks for the great suggestions. I've created some new issues for those specific features and will hopefully get around to them soon. Please subscribe to those issues to be updated on their progress

**Comment by Eds1989** [comment]
> @Eds1989 thanks for the great suggestions. I've created some new issues for those specific features and will hopefully get around to them soon. Please subscribe to those issues to be updated on their progress

No problem. Thanks for taking them into consideration.

Have subscribed to those issues and look forward to seeing what progress you might be able to make towards achieving them!

Thanks for all your efforts.
