### ISSUE TITLE
Feature: Disable Thumbnail Video Previews

### ISSUE THREAD

**Issue by Nadastorm** [OsaSoft/youtube-better-subscriptions#67]
On YouTube when the thumbnail video preview is going, you are unable to click the "Hide Video" button which can make hiding videos difficult. If there was an option to disable video previews or to have the "Hide Video" button always shown, that could fix the issue.

**Comment by OsaSoft** [comment]
Hey, thanks for the report.
Can you please provide some more info? Ive tested on both Firefox and Chrome and the "Mark watched" button seems to be working fine on both even when the thumbnail is showing the video preview

**Comment by Nadastorm** [comment]
Hi OsaSoft, looks like it was just on my end. I had an old bookmark saved that was https://www.youtube.com/feed/subscriptions/?disable_polymer=1 and that seems to be what was causing the issue. Sorry for the false alarm!

**Comment by OsaSoft** [comment]
Ah alright. Great you managed to resolve your issue!
Thanks for the feedback and for using my extension, hope you like it!
If anythinf else pops up or you have some cool ideas for improvement, be
sure to let me know

**Comment by WoLpH** [comment]
To clarify for others (and add a few google keywords), this issue occurs when you use YouTube Classic Mode.

**Comment by OsaSoft** [comment]
Thank @WoLpH, to add some more context, as I announced some time ago, non-polymer (or classic YT) was becoming too cumbersome to continue supporting, so for some time, the extension will work at least partially with it, but its entirely possible support for it will be dropped completely in a future version in order to simplify and clean up the code
