### ISSUE TITLE
Extension does not mark partly watched videos as watched

### ISSUE THREAD

**Issue by grandslammer** [OsaSoft/youtube-better-subscriptions#7]
Hey I recently noticed that the extension is not hiding videos that have not been watched til the very end. This is not expected behavior as most videos watched on YT are not watched to the very end!

Please update to fix this.

**Comment by OsaSoft** [comment]
Hey, thanks for the report.
I've recently noticed this as well, though the problem seems to be on YouTube's side. The extension is meant to hide partially watched videos, which at the moment it recognises by watching for that partially watched bar at the bottom of the thumbnail that YouTube puts there. However, last few days Ive noticed sometimes YouTube does not put there, while at other times it does.
So at the moment there really isnt much I can do about this. However, detecting watched and partially watched videos based solely on what YouTube provides is unsustainable in the long run, as any update to YouTube might break it, which is why Ive planned a new system for the version 1.0 release. 
Currently Im completely stumped with finishing up school and my thesis, so probably wont be able to do that before the end of January. 
So sorry, but youll just have to deal with this for a bit and hope YouTube stops bugging out.
