### ISSUE TITLE
Update "hide"/"mark watched" functionality.

### ISSUE THREAD

**Issue by surfarcher** [OsaSoft/youtube-better-subscriptions#78]
Youtube has added a "Hide" option to the dropdown menu on each video in the subscriptions page.

Example: ![image](https://user-images.githubusercontent.com/2238575/78848084-dacb8f00-7a4f-11ea-8174-2e362e356995.png)

Suggestion: It would be useful to leverage this new functionality in Better Subscriptions. I suggest changing the "mark watched" icon to trigger this functionality. An alternative would be to add a "Hide" icon next to the current "Mark Watched" icon.

The former would in effect completely resolve open issue #65.

**Comment by OsaSoft** [comment]
I dont want to use YTs hide, mainly for two reasons:
1) AFAIK there is no way to show those videos again
2) No idea how youtube uses hidden videos for their algorithms. Its entirely possible they could use it to not show you other similar videos or videos from the same channel, just because you hid some of their videos

Moving the hide button to be on the thumbnail itself would be possible. Might do that as a optional feature that can be enabled in the settings...

**Comment by surfarcher** [comment]
1. That's true, I can't find a way to unhide them on YTs either.

2. AFAI can tell it doesn't impact what's shown in your subscriptions at all. Based on a couple weeks use now, that is. I guess it's still possible it does and it'll turn up later.

**Comment by OsaSoft** [comment]
Closing as YT "hide video" will not be used
